[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

  external_node_modules = [
      "express",
      "body-parser",
      "cors",
      "serverless-http",
      "mime-types"
    ]
